return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",

  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    auto_install = true,

    ensure_installed = {
      "go",
      "c",
      "cpp",
      "c_sharp",
      "ruby",
      "rust",
      "java",
      "lua",
      "javascript",
      "typescript",
      "tsx",
      "html",
      "css",
      "scss",
      "sql",
      "yaml",
      "json",
      "regex",
      "markdown",
      "markdown_inline",
      "prisma",
      "graphql",
      "bash",
      "vim",
      "vimdoc",
      "query",
      "gitignore",
      "dockerfile",
    },
  },
}

